apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coforma-studio
resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:40e6bee317a7126b58dd49b26e7fd94e56a56754ef78c123667acb14d6754059
  name: ghcr.io/madfam-org/coforma-studio/web
  newName: ghcr.io/madfam-org/coforma-studio/web
