apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coforma-studio
resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:267f9aec8b403923333593d10b3e6cd283d42f6d0bf373ecba73d00579991ca3
  name: ghcr.io/madfam-org/coforma-studio/web
  newName: ghcr.io/madfam-org/coforma-studio/web
